# Generated by Django 5.2.3 on 2025-07-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_status',
            field=models.BooleanField(default=True),
        ),
    ]
