# Generated by Django 5.2.3 on 2025-07-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0004_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('assistant', 'Assistant'), ('general', 'General'), ('mentor', 'Mentor'), ('support', 'Support'), ('fun', 'Fun')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='vibe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
