# Generated by Django 5.2.3 on 2025-07-28 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_character_category_alter_character_vibe'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_messages', models.CharField(max_length=255)),
                ('bot_words', models.CharField(max_length=255)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='botapp.bot')),
            ],
        ),
    ]
