# Generated by Django 5.2.3 on 2025-08-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0006_botusages'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='agent_nature',
            field=models.CharField(blank=True, choices=[('flirty', 'Flirty'), ('professional', 'Professional'), ('funny', 'Funny'), ('friendly', 'Friendly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='agent_vibe',
            field=models.CharField(blank=True, choices=[('calm', 'Calm'), ('energetic', 'Energetic'), ('serious', 'Serious'), ('casual', 'Casual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='ai_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('claude-3.5-sonnet', 'Claude 3.5 Sonnet'), ('claude-3-haiku', 'Claude 3 Haiku'), ('gemini-pro', 'Gemini Pro'), ('llama-3.1-70b', 'Llama 3.1 70B')], default='gpt-4o-mini', max_length=50),
        ),
        migrations.AddField(
            model_name='bot',
            name='backup_frequency',
            field=models.CharField(choices=[('daily', 'Once a day'), ('every_2_days', 'Every 2 days'), ('weekly', 'Once a week'), ('monthly', 'Once a month')], default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='bot',
            name='conversation_memory',
            field=models.CharField(choices=[('short', 'Short (10 messages)'), ('medium', 'Medium (50 messages)'), ('long', 'Long (200 messages)'), ('unlimited', 'Unlimited')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='bot',
            name='response_speed',
            field=models.CharField(choices=[('fast', 'Fast'), ('balanced', 'Balanced'), ('quality', 'Quality')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='bot',
            name='server_location',
            field=models.CharField(choices=[('us-east', 'US East'), ('us-west', 'US West'), ('eu-west', 'Europe West'), ('asia-pacific', 'Asia Pacific'), ('india', 'India')], default='us-east', max_length=30),
        ),
        migrations.AddField(
            model_name='bot',
            name='server_type',
            field=models.CharField(choices=[('shared', 'Shared'), ('vps', 'VPS'), ('dedicated', 'Dedicated')], default='shared', max_length=20),
        ),
        migrations.AddField(
            model_name='bot',
            name='storage_size',
            field=models.CharField(choices=[('1gb', '1 GB'), ('5gb', '5 GB'), ('10gb', '10 GB'), ('25gb', '25 GB'), ('50gb', '50 GB'), ('100gb', '100 GB')], default='1gb', max_length=20),
        ),
    ]
