# Generated by Django 5.2.4 on 2025-08-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contact_number_1',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact_number_2',
        ),
    ]
