# Generated by Django 5.2.4 on 2025-08-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_rename_contact_number_1_order_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line_1',
            new_name='address_line',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_line_2',
        ),
    ]
