# Generated by Django 5.2.4 on 2025-09-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0008_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_proof',
            field=models.ImageField(blank=True, null=True, upload_to='transaction_proofs/'),
        ),
    ]
